import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavLinks from "./ui/dashboard/nav-links";
import Navbar from "./ui/dashboard/navbar";
import { signOut } from '@/auth';
import styles from './ui/button.module.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
        
        
        <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}

/*
<form
          action={async () => {
            'use server';
            await signOut();
          }}
        >
          <button className={styles.button}>            
            <div >Sign Out</div>
          </button>
        </form>
*/